### ISSUE TITLE
NET6.0

### ISSUE THREAD

**Issue by QualityRobD** [RockLib/RockLib.Logging#99]
With [4.6.1 already EOL](https://endoflife.date/dotnetfx) and unsupported is there a plan to upgrade this library to NET6.0 or create a new one leveraging the new framework?

If so, is there an ETA?

**Comment by eslutz** [comment]
Hi @QualityRobD, as of today, all four RockLib.Logging packages have been updated and released.  The supported targets are net6.0, netcoreapp3.1, and net48.

- [RockLib.Logging Version 4.0.1](https://github.com/RockLib/RockLib.Logging/releases/tag/RockLib.Logging.4.0.1)
- [RockLib.Logging.AspNetCore version 4.0.0](https://github.com/RockLib/RockLib.Logging/releases/tag/RockLib.Logging.AspNetCore.4.0.0) 
- [Release RockLib.Logging.Microsoft.Extensions version 2.0.0](https://github.com/RockLib/RockLib.Logging/releases/tag/RockLib.Logging.Microsoft.Extensions.2.0.0)
- [Release RockLib.Logging.Moq version 2.0.0](https://github.com/RockLib/RockLib.Logging/releases/tag/RockLib.Logging.Moq.2.0.0)
